spring.application.name=users
logging.level.root=${LOGGING_LEVEL_ROOT:INFO}
logging.level.com.oscarfndez=${LOGGING_LEVEL_APP:INFO}
logging.level.org.springframework.security=${LOGGING_LEVEL_SECURITY:WARN}
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n

spring.datasource.url=jdbc:postgresql://localhost:5432/users
# Configuracion de Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
flyway.baseline-on-migrate=true
flyway.ignore-ignored-migrations=true
flyway.ignore-missing-migrations=true
flyway.ignore-future-migrations=true
token.signing.key=413F4428472B4B6250655368566D5970337336763979244226452948404D6351
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
spring.jms.pub-sub-domain=true
spring.activemq.broker-url=${SPRING_ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
spring.activemq.user=${SPRING_ACTIVEMQ_USER:admin}
spring.activemq.password=${SPRING_ACTIVEMQ_PASSWORD:admin}
user.events.enabled=${USER_EVENTS_ENABLED:true}
user.events.topic=${USER_EVENTS_TOPIC:games-collection.user-events}
